routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['prefix' => 'administrator', 'middleware' => 'auth'], function() {
    Route::get('/home', 'ProductController@index');
    Route::resource('category', 'CategoryController')->except(['create', 'show']);
    Route::resource('product', 'ProductController');
    
});
//export import
Route::get('/product/export_excel', 'ProductController@export_excel');
Route::post('/product/import_excel', 'ProductController@import_excel');

resources/views/layouts/module/header.blade.php
<header class="app-header navbar">
    <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <a class="navbar-brand" href="#">
    <img class="navbar-brand-full" src="{{asset('assets/img/1.png')}}" width="89" height="25" alt="Plat Recoginition">
        <img class="navbar-brand-minimized" src="{{ asset('assets/img/2.png') }}" width="30" height="30" alt="CoreUI Logo">
    </a>
    <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
        <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item d-md-down-none">
            <a class="nav-link" href="#">
                <i class="icon-location-pin"></i>
            </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                <img class="img-avatar" src="{{ asset('assets/img/avatars/6.jpg') }}" alt="admin@bootstrapmaster.com">
            </a>
        <div class="dropdown-menu dropdown-menu-right">
            <div class="dropdown-header text-center">
                <strong>Account</strong>
            </div>
            <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">
                <i class="fa fa-lock"></i> Logout
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </div>
        </li>
    </ul>
</header>

resources/views/layouts/module/sidebar.blade.php
<nav class="sidebar-nav">
    <ul class="nav">
        <li class="nav-title">MANAJEMEN PLATE</li>
        <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#">
                <i class="nav-icon icon-settings"></i> Pengambilan Data
            </a>
            <ul class="nav-dropdown-items">
                <li class="nav-item">
                    <a class="nav-link" href="/product/export_excel">
                        <i class="nav-icon icon-puzzle"></i> Export Data
                    </a>
                </li>
                
            </ul>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('product.index') }}">
            <i class="nav-icon icon-drop"></i> Data Pemilik
            </a>
        </li>
    </ul>
</nav>