routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['prefix' => 'administrator', 'middleware' => 'auth'], function() {
    Route::get('/home', 'ProductController@index');
    Route::resource('category', 'CategoryController')->except(['create', 'show']);
    Route::resource('product', 'ProductController');
    
});
//export import
Route::get('/product/export_excel', 'ProductController@export_excel');
Route::post('/product/import_excel', 'ProductController@import_excel');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
class Product extends Model
{
    protected $guarded =[];

    public function setPlatAttribute($value){

    $this->attributes['no_plat'] = Str::no_plat($value); 
    }
    public function getStatusLabelAttribute(){
        if ($this->status == 1){
            return '<span class="badge badge-secondary">Lunas</span>';
        }
        return '<span class="badge badge-success">Belum Lunas</span>';
    }
    public function getStatusLamaCicilanAttribute(){
        if ($this->lama_cicilan == 1){
            return '<span class="badge badge-secondary">12</span>';
        } else if($this->lama_cicilan == 2){
            return '<span class="badge badge-secondary">24</span>';
        } else if($this->lama_cician == 3 ){
            return '<span class="badge badge-secondary">35</span>';
        }else if($this->lama_cicilan == 4){
            return '<span class="badge badge-secondary">42</span>';
        }
        return '<span class="badge badge-secondary">60</span>';
    }
    public function category(){
        return $this->belongsTo(Category::class);
    }
    protected static $logFillable = true;

    protected $table = "products";
    protected $fillable = [
        'no_plat',
        'lat',
        'lon',
        'image_plat',
        'name',
        'jenis_kendaraan',
        'merk',
        'lama_cicilan',
        'warna',
        'alamat',
        'informasi_id',
        'status',
        'penunggakan',
        'type_kendaraan'
    ];
    

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Category;
use Illuminate\Support\Str;
use File;
use App\Exports\ProductExport;
use App\Imports\ProductImport;
use Maatwebsite\Excel\Facades\Excel;

class ProductController extends Controller
{
    public function product(){
        $product = Product::all();
        return response()->json([
            'message' => 'berhasil',
            'product' => $product
        ], 200);
    }
    public function search($param){
        $post = Product::where('no_plat',$param)->orWhere('name', 'like', '%' . $param . '%')->get();
        if (! $post) {
          return response()->json([
            'message' => 'not found'
          ],404);
        } else {
            return response()->json([
                'message' => 'berhasil',
                'product' => $post
              ],200);
        }

    }
    public function index(){
        
        
           $product = Product::all(); 
    if (request()->q != '') {
        
        $product = $product->where('no_plat', 'LIKE', '%' . request()->q . '%');
    }
    
    //   $product = Product::all()->paginate(5);
    
    return view('products.index', compact('product'));
    }
    public function create(){
        // $category = Category::orderBy('no_plat' , 'DESC');
        $product = Product::all();
        return View('products.create', compact('product'));
    }
    public function storeMobile(Request $request){
       
        return Product::create($request->all());
        
        if($request->hashFile('image_plat')){
            $file = $request->file('image_plat');
            $filename = time() . Str::no_plat($request->name) . '.' . $file->getClientOriginalExtension();
            $file->storeAs('public/products', $filename);
        }
        return redirect(route('product.index'))->with(['success' => 'Data Baru Ditambahkan']);
    }
    public function show($no_plat){
        $post = Product::where('no_plat',$no_plat)->first();
        if (! $post) {
          return response()->json([
            'message' => 'no_plat not found'
          ],404);
        } else {
            return response()->json([
                'message' => 'berhasil',
                'data' => $post
              ],200);
        }

    }
    public function update(Request $request, $no_plat)
    {
        $post = Product::where('no_plat',$no_plat)->first();

        if ($post) {
        $post->update($request->all());
            return response()->json([
                'message' => 'Updated',
                'data' => $post
            ], 200);
        }

        return response()->json([
        'message' => 'No Plat not found',
        ], 404);
    }
    public function delete(Requst $request , $id){
        $product = Product::find($id);

        if ($product) {
            $product->delete($request->all());
            return response()->json([
                'message' => 'delete',
                'data' => $product
            ], 200);
        }else{
            return response()->json([
                'message' => 'Id Not Found',
                ], 404);
        }
    }
    public function store(Request $request){
        Product::create([
            'name' => e($request->input('name')),
            'no_plat' => e($request->input('no_plat')),
            'catagory_id' => e($request->input('catagory_id')), 
            'jenis_kendaraan' => e($request->input('jenis_kendaraan')),
            'lama_cicilan' => e($request->input('lama_cicilan')),
            'image_plat' => e($request->input('image_plat')),
            'type_kendaraan' => e($request->input('type_kendaraan')),
            'alamat' => e($request->input('alamat')),
            'merk' => e($request->input('merk')),
            'status' => e($request->input('status')),
            'lama_cicilan' => e($request->input('lama_cicilan')),
            'penunggakan' => e($request->input('penunggakan')),
            'lat' => e($request->input('lat')),
            'lon' => e($request->input('lon')),
            'warna' => e($request->input('warna'))  

        ]);
                return redirect(route('product.index'))->with(['success' => 'Data Baru Ditambahkan']);
            
    }
    public function destroy($id){
        $product = Product::find($id);
        File::delete(storage_path('app/public/products/' . $product->image_plat));
        $product->delete();
        return redirect(route('product.index'))->with(['success' => 'Produk Sudah Dihapus']);
    }
    public function edit($no_plat){
        $product = Product::find($no_plat);
        return redirect(route('product.edit'))->with(['success' => 'Produk Sudah Dihapus']);
    }
    public function updateProduct(Request $request, $no_plat , $id){
        $product = Product::find($id);
        $product->name = e($request->input('name'));
        $product->no_plat = e($request->input('no_plat'));
        $product->save();
        return redirect()->route('product.plat');
    }
    public function export_excel()
	{
		return Excel::download(new ProductExport, 'Data.xls');
    }
    public function import_excel(Request $request) 
	{
		
		$this->validate($request, [
			'file' => 'required|mimes:csv,xls,xlsx'
		]);
		$file = $request->file('file');
		$nama_file = rand().$file->getClientOriginalName();
		$file->move('file_product',$nama_file);
		Excel::import(new ProductImport, public_path('/file_product/'.$nama_file));
		Session::flash('sukses','Data Siswa Berhasil Diimport!');
			return redirect('/product');
	}
}

resources/views/products/create.blade.php
@extends('layouts.admin')

@section('title')
    <title>Tambah Data</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item active">Data Plat</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            <form action="{{ route('product.store') }}" method="post" enctype="multipart/form-data" >
                @csrf
                <div class="row">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Tambah Data</h4>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">Nama Pemilik</label>
                                    <input type="text" name="name" class="form-control" value="{{ old('name') }}" required>
                                    <p class="text-danger">{{ $errors->first('name') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="description">No_plat</label>
                                    <textarea name="no_plat" id="no_plat" class="form-control">{{ old('no_plat') }}</textarea>
                                    <p class="text-danger">{{ $errors->first('no_plat') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="penunggakan">Penunggakan</label>
                                    <textarea name="penunggakan" id="penunggakan" class="form-control">{{ old('penunggakan') }}</textarea>
                                    <p class="text-danger">{{ $errors->first('penunggakan') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="description">Type Kendaraan</label>
                                    <textarea name="type_kendaraan" id="type_kendaraan" class="form-control">{{ old('type_kendaraan') }}</textarea>
                                    <p class="text-danger">{{ $errors->first('type_kendaraan') }}</p>
                                </div>
                                <div class="form-group">
                                <label for="description">Alamat</label>
                                    <textarea name="alamat" id="alamat" class="form-control">{{ old('alamat') }}</textarea>
                                    <p class="text-danger">{{ $errors->first('alamat') }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="status">Status</label>
                                    <select name="status" class="form-control" required>
                                        <option value="1" {{ old('status') == '1' ? 'selected':'' }}>Lunas</option>
                                        <option value="2" {{ old('status') == '2' ? 'selected':'' }}>Belum Lunas</option>
                                        <option value="0" {{ old('status') == '0' ? 'selected':'' }}>Menunggak</option>
                                    </select>
                                    <p class="text-danger">{{ $errors->first('status') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="lama_cicilan">Lama Cicilan</label>
                                    <select name="lama_cicilan" class="form-control" required>
                                        <option value="1" {{ old('lama_cicilan') == '1' ? 'selected':'' }}>12</option>
                                        <option value="2" {{ old('lama_cicilan') == '2' ? 'selected':'' }}>24</option>
                                        <option value="3" {{ old('lama_cicilan') == '3' ? 'selected':'' }}>35</option>
                                        <option value="4" {{ old('lama_cicilan') == '4' ? 'selected':'' }}>42</option>
                                        <option value="0" {{ old('lama_cicilan') == '0' ? 'selected':'' }}>60</option>
                                    </select>
                                    <p class="text-danger">{{ $errors->first('lama_cicilan') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="price">Jenis Kendaraan</label>
                                    <input type="text" name="jenis_kendaraan" class="form-control" value="{{ old('jenis_kendaraan') }}" required>
                                    <p class="text-danger">{{ $errors->first('jenis_kendaraan') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="merk">Merk
                                    </label>
                                    <input type="text" name="merk" class="form-control" value="{{ old('merk') }}" required>
                                    <p class="text-danger">{{ $errors->first('merk') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="warna">Warna
                                    </label>
                                    <input type="text" name="warna" class="form-control" value="{{ old('warna') }}" required>
                                    <p class="text-danger">{{ $errors->first('warna') }}</p>
                                </div>
                                <div class="form-group text-center">
                                <input type="submit" name="Tambah Data" class="btn btn-primary input-lg" value="Tambah Data" />
                                </div> 
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</main>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.admin')

@section('title')
    <title>Tambah Data</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item active">Data Plat</li>
    </ol>
    <div class="card-body">
        <from method="post" action="{{ route('product.plat') }}">
            @method('PUT')
            @csrf
            <div class="from-group">
                <label for="name">Name</label>
                <input type="text" value="{{ $product->name }}" name="name" class="form-control" id="name" aria-describedby="nameHelp" placeholder="Enter name">
            </div>
            <div class="from-group">
                <label for="name">Name</label>
                <input type="text" value="{{ $product->no_plaot }}" name="no_plat" class="form-control" id="no_plat" aria-describedby="no_platHelp" placeholder="Enter No Plat">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </from>
    </div>
</main>
@endsection

@section('js')
@endsection

resources/views/products/index.blade.php
@extends('layouts.admin')

@section('title')
    <title>Data Pemilik</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item active">Product</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">
                            Data Pemilik
                            <div class="float-right">
                                <button  class="btn btn-primary btn-sm" data-toggle="modal" data-target="#importExcel">
                                    Import Data
                                </button>
                                <a href="{{ route('product.create') }}" class="btn btn-primary btn-sm">Tambah</a>
                                
                                </div>
                            </h4>
                            
                            {{-- notifikasi form validasi --}}
                                @if ($errors->has('file'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('file') }}</strong>
                                </span>
                                @endif
                        
                                {{-- notifikasi sukses --}}
                                @if ($sukses = Session::get('sukses'))
                                <div class="alert alert-success alert-block">
                                    <button type="button" class="close" data-dismiss="alert">×</button> 
                                    <strong>{{ $sukses }}</strong>
                                </div>
                                @endif
                        <!-- Import Excel -->
                        <div class="modal fade" id="importExcel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <form method="post" action="/product/import_excel" enctype="multipart/form-data">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Import Excel</h5>
                                        </div>
                                        <div class="modal-body">
                
                                            <!-- {{ csrf_field() }} -->
                                            @csrf
                
                                            <label>Pilih file excel</label>
                                            <div class="form-group">
                                                <input type="file" name="file" required="required">
                                            </div>
                
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Import</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        </div>
                        <div class="card-body">
                            @if (session('success'))
                                <div class="alert alert-success">{{ session('success') }}</div>
                            @endif

                            @if (session('error'))
                                <div class="alert alert-danger">{{ session('error') }}</div>
                            @endif
                            

                            
                            <form action="{{ route('product.index') }}" method="get">
                                <div class="input-group mb-3 col-md-3 float-right">
                                    
                                    <input type="text" name="q" class="form-control" placeholder="Cari..." value="{{ request()->q }}">
                                    <div class="input-group-append">
                                        <button class="btn btn-secondary" type="button">Cari</button>
                                    </div>
                                </div>
                            </form>
                            <div class="table-responsive">
                                <table class="table table-hover table-bordered">
                                    <thead>
                                        <tr>
                                            
                                            
                                            <th>Plate</th>
                                            <th>Pemilik</th>
                                            <th>Status</th>
                                            <th>Jenis Kendaraan</th>
                                            <th>Merk</th>
                                            <th>Type Kendaraan</th>
                                            <th>Alamat</th>
                                            <th>Lama Cicilan</th>
                                            <th>Tunggakan</th>
                                            <th>Option</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($product ?? ''  as $row)
                                        <tr>
                                           
                                            <td>{{ $row->no_plat }}</td>
                                            <td>
                                                <strong>{{ $row->name }}</strong><br>
                                                <label> <span class="badge badge-info">{{ $row->create}}</span></label><br>
                                            </td>
                                            <td>{{ $row->status }}</td>
                                            <td>{!! $row->jenis_kendaraan !!}</td>
                                            <td>{{ $row->merk }}</td>
                                            <td>{{ $row->type_kendaraan }}</td>
                                            <td>{{ $row->alamat }}</td>
                                            <td>{{ $row->lama_cicilan }}</td>
                                            <td>
                                            {{ $row->penunggakan }}
                                                </td>
                                            <td>
                                                
                                                <form action="{{ route('product.destroy', $row->id) }}" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <!-- <a href="{{ route('product.edit', $row->no_plat) }}" class="btn btn-warning btn-sm">Edit</a> -->
                                                    <button class="btn btn-danger btn-sm">Hapus</button>
                                                </form>
                                            </td>
                                        </tr>
                                        @empty
                                        <tr>
                                            <td colspan="5" class="text-center">Tidak ada data</td>
                                        </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                          
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection